runtime: python39
entrypoint: gunicorn -b :$PORT main:app

handlers:
  - url: /static
    static_dir: static  # Replace `static` with your static files directory if needed
    secure: always

  - url: /.*
    script: auto

env_variables:
  OPENAI_PROJECT_API_KEY: 'sk-proj-T038TA3CGZoVj9GteknsT3BlbkFJevhizpZ0tb5M1SSCigTR'